services:
  web:
    build:
      context: .
      target: dev
    container_name: bytebio-web-dev
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next

volumes:
  node_modules:
  next_cache:
